# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chattingo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chattingo-backend
  template:
    metadata:
      labels:
        app: chattingo-backend
    spec:
      containers:
        - name: chattingo-backend
          image: chattingo-backend:latest # Replace with your image repo if needed
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              value: "z9iomEpv/QtMfd2HTXnLzGt/7+R7I38m9k0T4L7GJa0="
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://chattingo-mysql:3306/chattingo_db?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "test@123"
            - name: CORS_ALLOWED_ORIGINS
              value: "http://52.58.3.148:3000,http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001"
            - name: CORS_ALLOWED_METHODS
              value: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
            - name: CORS_ALLOWED_HEADERS
              value: "*"
            - name: SPRING_PROFILES_ACTIVE
              value: "development"
            - name: SERVER_PORT
              value: "8080"

# Backend Service
---
apiVersion: v1
kind: Service
metadata:
  name: chattingo-backend
spec:
  selector:
    app: chattingo-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
